<?php
// 上海
$config['121'] = [
    'avg_price' => 32906,
    'data' => [
        [
            'section_name' => '闵行',
            'block_name' => '莘庄',
            'cell_name' => '上海康城',
            'cell_avg_price' => '19211',
            'on_sale_count' => '253',
            'img_name' => '121_kangcheng001',
        ],
        [
            'section_name' => '浦东',
            'block_name' => '三林',
            'cell_name' => '三林世博家园',
            'cell_avg_price' => '27731',
            'on_sale_count' => '176',
            'img_name' => '121_jiayuan001',
        ],
        [
            'section_name' => '浦东',
            'block_name' => '北蔡',
            'cell_name' => '大华锦绣华城',
            'cell_avg_price' => '40492',
            'on_sale_count' => '166',
            'img_name' => '121_jinxiu001',
        ],
        [
            'section_name' => '松江',
            'block_name' => '松江大学城',
            'cell_name' => '保利西子湾',
            'cell_avg_price' => '21794',
            'on_sale_count' => '121',
            'img_name' => '121_xiziwan001',
        ],
        [
            'section_name' => '松江',
            'block_name' => '泗泾',
            'cell_name' => '新凯家园',
            'cell_avg_price' => '18469',
            'on_sale_count' => '156',
            'img_name' => '121_xinkai001',
        ],
//        [
//            'section_name' => '宝山',
//            'block_name' => '通河',
//            'cell_name' => '泗塘新村',
//            'cell_avg_price' => '22915',
//            'on_sale_count' => '298',
//            'img_name' => '121_sitang001',
//        ],
//        [
//            'section_name' => '宝山',
//            'block_name' => '张庙',
//            'cell_name' => '呼玛新村',
//            'cell_avg_price' => '26043',
//            'on_sale_count' => '270',
//            'img_name' => '121_huma001',
//        ],
//        [
//            'section_name' => '徐汇',
//            'block_name' => '华东理工',
//            'cell_name' => '梅陇新村',
//            'cell_avg_price' => '27018',
//            'on_sale_count' => '454',
//            'img_name' => '121_meilong001',
//        ],
        [
            'section_name' => '浦东',
            'block_name' => '三林',
            'cell_name' => '凌兆新村',
            'cell_avg_price' => '25784',
            'on_sale_count' => '144',
            'img_name' => '121_lingzhao001',
        ],
        [
            'section_name' => '杨浦',
            'block_name' => '中原',
            'cell_name' => '市光四村',
            'cell_avg_price' => '29103',
            'on_sale_count' => '126',
            'img_name' => '121_shiguang001',
        ],
    ]
];

// 杭州
$config['2316'] = [
    'avg_price' => 20317,
    'data' => [
        [
            'section_name' => '西湖',
            'block_name' => '文新',
            'cell_name' => '世纪新城',
            'cell_avg_price' => '29419',
            'on_sale_count' => '98',
            'img_name' => '2316_shijixincheng001',
        ],
        [
            'section_name' => '西湖',
            'block_name' => '文新',
            'cell_name' => '嘉绿西苑',
            'cell_avg_price' => '22469',
            'on_sale_count' => '34',
            'img_name' => '2316_jialv001',
        ],
        [
            'section_name' => '江干',
            'block_name' => '下沙沿江',
            'cell_name' => '世茂江滨花园',
            'cell_avg_price' => '8983',
            'on_sale_count' => '133',
            'img_name' => '2316_shimaojiangbin001',
        ],
        [
            'section_name' => '江干',
            'block_name' => '下沙沿江',
            'cell_name' => '保利东湾',
            'cell_avg_price' => '9455',
            'on_sale_count' => '229',
            'img_name' => '2316_baolidongwan001',
        ],
        [
            'section_name' => '西湖',
            'block_name' => '三墩',
            'cell_name' => '金地自在城',
            'cell_avg_price' => '14837',
            'on_sale_count' => '265',
            'img_name' => '2316_jindi001',
        ],
        [
            'section_name' => '江干',
            'block_name' => '下沙沿江',
            'cell_name' => '多蓝水岸',
            'cell_avg_price' => '8231',
            'on_sale_count' => '76',
            'img_name' => '2316_duolan001',
        ],
        [
            'section_name' => '江干',
            'block_name' => '三里亭',
            'cell_name' => '三里亭',
            'cell_avg_price' => '15350',
            'on_sale_count' => '121',
            'img_name' => '2316_sanliting001',
        ],
        [
            'section_name' => '西湖',
            'block_name' => '三墩',
            'cell_name' => '都市水乡',
            'cell_avg_price' => '12429',
            'on_sale_count' => '70',
            'img_name' => '2316_dushishuixiang001',
        ],
        [
            'section_name' => '余杭',
            'block_name' => '闲林',
            'cell_name' => '闲林山水',
            'cell_avg_price' => '8193',
            'on_sale_count' => '331',
            'img_name' => '2316_shanshui001',
        ],
        [
            'section_name' => '上城',
            'block_name' => '南星',
            'cell_name' => '春江花月',
            'cell_avg_price' => '29085',
            'on_sale_count' => '55',
            'img_name' => '2316_huayue001',
        ],
    ]
];

// 苏州
$config['3'] = [
    'avg_price' => 12888,
    'data' => [
        [
            'section_name' => '吴中',
            'block_name' => '越溪',
            'cell_name' => '招商小石城',
            'cell_avg_price' => '9088',
            'on_sale_count' => '62',
            'img_name' => '3_zhaoshang001',
        ],
        [
            'section_name' => '吴中',
            'block_name' => '郭巷',
            'cell_name' => '湖岸名家',
            'cell_avg_price' => '12127',
            'on_sale_count' => '105',
            'img_name' => '3_mingjia001',
        ],
        [
            'section_name' => '吴中',
            'block_name' => '木渎',
            'cell_name' => '枫华紫园',
            'cell_avg_price' => '9499',
            'on_sale_count' => '66',
            'img_name' => '3_ziyuan001',
        ],
        [
            'section_name' => '新区',
            'block_name' => '狮山',
            'cell_name' => '嘉业阳光假日',
            'cell_avg_price' => '11349',
            'on_sale_count' => '74',
            'img_name' => '3_jiaye001',
        ],
        [
            'section_name' => '姑苏',
            'block_name' => '彩云街道',
            'cell_name' => '三元三村',
            'cell_avg_price' => '11015',
            'on_sale_count' => '47',
            'img_name' => '3_sanyuan001',
        ],
        [
            'section_name' => '吴中',
            'block_name' => '木渎',
            'cell_name' => '诚河新旅城',
            'cell_avg_price' => '10308',
            'on_sale_count' => '79',
            'img_name' => '3_chenghe001',
        ],
        [
            'section_name' => '吴中',
            'block_name' => '城南街道',
            'cell_name' => '阳光水韵花园',
            'cell_avg_price' => '10232',
            'on_sale_count' => '55',
            'img_name' => '3_shuiyunhuayuan001',
        ],
        [
            'section_name' => '园区',
            'block_name' => '玲珑',
            'cell_name' => '玲珑湾花园',
            'cell_avg_price' => '20294',
            'on_sale_count' => '115',
            'img_name' => '3_linglongwan001',
        ],
        [
            'section_name' => '新区',
            'block_name' => '枫桥',
            'cell_name' => '理想城',
            'cell_avg_price' => '8335',
            'on_sale_count' => '99',
            'img_name' => '3_lixiangcheng001',
        ],
        [
            'section_name' => '园区',
            'block_name' => '双湖',
            'cell_name' => '大湖城邦',
            'cell_avg_price' => '14125',
            'on_sale_count' => '53',
            'img_name' => '3_dahuchengbang001',
        ],
    ]
];

// 南京
$config['267'] = [
    'avg_price' => 17045,
    'data' => [
        [
            'section_name' => '浦口',
            'block_name' => '桥北',
            'cell_name' => '天润城',
            'cell_avg_price' => '10829',
            'on_sale_count' => '644',
            'img_name' => '267_tianruncheng001',
        ],
        [
            'section_name' => '浦口',
            'block_name' => '沿江',
            'cell_name' => '威尼斯水城',
            'cell_avg_price' => '10902',
            'on_sale_count' => '550',
            'img_name' => '267_weinisi001',
        ],
        [
            'section_name' => '浦口',
            'block_name' => '桥北',
            'cell_name' => '明发滨江新城',
            'cell_avg_price' => '10113',
            'on_sale_count' => '900',
            'img_name' => '267_binjiangxincheng001',
        ],
        [
            'section_name' => '栖霞',
            'block_name' => '仙林',
            'cell_name' => '亚东城',
            'cell_avg_price' => '19588',
            'on_sale_count' => '126',
            'img_name' => '267_yadongcheng001',
        ],
        [
            'section_name' => '浦口',
            'block_name' => '桥北',
            'cell_name' => '旭日爱上城',
            'cell_avg_price' => '10887',
            'on_sale_count' => '155',
            'img_name' => '267_xuri001',
        ],
        [
            'section_name' => '江宁',
            'block_name' => '竹山路',
            'cell_name' => '武夷绿洲',
            'cell_avg_price' => '15744',
            'on_sale_count' => '170',
            'img_name' => '267_wuyilvzhou001',
        ],
        [
            'section_name' => '江宁',
            'block_name' => '岔路口',
            'cell_name' => '天地新城',
            'cell_avg_price' => '13573',
            'on_sale_count' => '298',
            'img_name' => '267_tiandixincheng001',
        ],
        [
            'section_name' => '浦口',
            'block_name' => '沿江',
            'cell_name' => '江岸水城',
            'cell_avg_price' => '9623',
            'on_sale_count' => '144',
            'img_name' => '267_jiangan001',
        ],
        [
            'section_name' => '栖霞',
            'block_name' => '马群',
            'cell_name' => '百水芊城',
            'cell_avg_price' => '12086',
            'on_sale_count' => '214',
            'img_name' => '267_baishui001',
        ],
    ]
];